[package]
name = "ham_os"
version = "0.1.0"
edition = "2018"
authors = ["Reed Hamilton <hamiltonreed33@gmail.com>"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9"
